//std.event.event,tests.event_d,tests.orvid,tests.phobos_signal,tests.presenter_first,tests.presenter_first2
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import unit_threaded;

int main(string[] args)
{
    return args.runTests!(
                          "std.event.event",
                          "tests.event_d",
                          "tests.orvid",
                          "tests.phobos_signal",
                          "tests.presenter_first",
                          "tests.presenter_first2"
                          );
}
